# Generated by Django 6.0.4 on 2026-05-06 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('blob_name', models.CharField(max_length=1000, unique=True)),
                ('azure_url', models.URLField(max_length=2000)),
                ('file_size', models.PositiveBigIntegerField(help_text='File size in bytes')),
                ('description', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'uploaded_at'], name='documents_p_user_id_8d6028_idx'), models.Index(fields=['user', 'is_active'], name='documents_p_user_id_cb7916_idx')],
            },
        ),
    ]
