# Generated by Django 6.0.4 on 2026-05-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_uploadbatch_pdfdocument_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='description',
        ),
    ]
