# Generated by Django 6.0.4 on 2026-05-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_pdfdocument_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadbatch',
            name='search_all',
            field=models.BooleanField(default=True, help_text='If true, search against all PDFs. If false, search only this batch.'),
        ),
    ]
