"""
Django settings for pdf_storage project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')

# Azure settings
AZURE_CONNECTION_STRING = config('AZURE_CONNECTION_STRING')
AZURE_CONTAINER_NAME = config('AZURE_CONTAINER_NAME')

# pdf_storage/settings.py

# Cosmos DB Config (Default to dummy values)
COSMOS_URI = config('COSMOS_URI')
COSMOS_KEY = config('COSMOS_KEY')
COSMOS_DATABASE = config('COSMOS_DATABASE')
COSMOS_CONTAINER = config('COSMOS_CONTAINER')
PARTITION_KEY_PATH = config('PARTITION_KEY_PATH')

WEBHOOK_BASE_URL = config('WEBHOOK_BASE_URL')
WEBHOOK_SECRET = config('WEBHOOK_SECRET')

# File upload settings
MAX_UPLOAD_SIZE = 10 * 1024 * 1024     # 10MB per file
ALLOWED_FILE_TYPES = ['application/pdf']

CORS_ALLOW_ALL_ORIGINS = True if DEBUG else False 

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    # Your apps
    'authentication',
    'documents',
    'search',
]

MIDDLEWARE = [
    'pdf_storage.middleware.JSONErrorMiddleware',   # ← first in the list
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdf_storage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdf_storage.wsgi.application'


from urllib.parse import urlparse, parse_qsl

tmpPostgres = urlparse(config("DATABASE_URL"))

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        #                               ↑
        #              Everything requires login by default
        #              We will override where needed
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    'EXCEPTION_HANDLER': 'pdf_storage.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/hour',
        'user': '200/hour',
        'upload': '50/day',
        'pdfs': '10/minute',
        'login': '10/minute',
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Resume Scoring API',
    'DESCRIPTION': 'API for uploading CVs and matching against job descriptions',
    'VERSION': '1.0.0',
}

# Configure Simple JWT lifetimes & settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),       # Short lifetime for security
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Long lifetime for seamless UX
    'ROTATE_REFRESH_TOKENS': True,                    # Issues a new refresh token on use
    'BLACKLIST_AFTER_ROTATION': True,                 # Prevents old refresh tokens from being reused
    'AUTH_HEADER_TYPES': ('Bearer',),                 # Uses "Bearer <token>" instead of "Token <token>"
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # Password cannot be too similar to username/email
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email'),
            'max_similarity': 0.5,
            #                    ↑
            # 0.5 means if password is more than 50% similar
            # to username or email it is rejected
        }
    },
    {
        # Minimum length (we also check in serializer but belt and suspenders)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        # Rejects common passwords like "password123", "qwerty" etc.
        # Django ships with a list of 20,000 common passwords
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        # Password cannot be entirely numeric
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
