# Generated by Django 6.0.4 on 2026-05-07 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0004_alter_uploadbatch_search_all'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.CharField(max_length=500)),
                ('score', models.FloatField()),
                ('rank', models.PositiveIntegerField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='documents.uploadbatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['batch', 'rank'],
                'indexes': [models.Index(fields=['batch', 'rank'], name='search_sear_batch_i_ef986f_idx'), models.Index(fields=['user', 'batch'], name='search_sear_user_id_cbc228_idx'), models.Index(fields=['candidate_id'], name='search_sear_candida_1134a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'candidate_id'), name='unique_candidate_per_batch')],
            },
        ),
    ]
